name: food-delivery-stack

services:
  # Backend
  laravel.test:
    build:
      context: ./backend/vendor/laravel/sail/runtimes/8.5
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.5/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
    volumes:
      - './backend:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.4'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail

  # Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sail
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE=http://localhost:8000/api

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local